server:
  port: 8081
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/secret?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: swkim
    password: qwerasdf

  #    url: jdbc:h2:mem:backofficeDb
#    url: jdbc:h2:/Users/swkim/h2db;AUTO_SERVER=true
#    driver-class-name: org.h2.Driver
#    username: root
#    password: '1234'

  jpa:
    hibernate:
      # none: 아무것도 실행하지 않음
      # create-drop: SessionFactory 시작시점에 drop후 create를 실행하여, SessionFactory 종료시 drop을 실행
      # update: 변경된 스키마를 적용
      # create: SessionFactory 시작 시점에 drop을 실행하고 create를 실행
      # validate: 변경된 스키마가 존재하면 변경사항을 출력하고 app을 종료
      ddl-auto: update
      # use-new-id-generator-mappings: false

    # Spring Application 실행시점에 Hibernate에서 자동으로 DDL을 생성하여, 필요한 Database의 Table설정들을 자동으로 실행
    generate-ddl: true

    properties:
      format_sql: true
      hibernate:
        show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mustache:
    suffix: .html

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
  file:
    name: ./logs/spring-jpa.log