POST http://localhost:8081/api/notice
Content-Type: application/json

{
  "title": "1112103120312032103103",
  "contents": "1112103120312214012041204012401240123-240215021502105120432103103-2-2-30"
}
###
POST http://localhost:8081/api/notice
Content-Type: application/json
{
  "title": "타이틀3",
  "contents": "contents4"
}

###
GET http://localhost:8081/api/notice/3

###
PUT http://localhost:8081/api/notice/1
Content-Type: application/json

{
  "title": "타이틀345",
  "contents": "contents345"
}

###
PATCH http://localhost:8081/api/notice/1/hits
Content-Type: application/json


###
DELETE http://localhost:8081/api/notice/1
Content-Type: application/json

###
DELETE http://localhost:8081/api/notice
Content-Type: application/json

{
  "idList": [1,2]
}

###
GET http://localhost:8081/api/notice/latest/3

###
POST http://localhost:8081/api/user
Content-Type: application/json

{
  "email" : "test2@test.com",
  "userName" : "test",
  "password" : "12341234",
  "phone" : "010-4939-2394"
}

###
PUT http://localhost:8081/api/user/2
Content-Type: application/json

{
"phone" : "010-1234-5678"
}

###
GET http://localhost:8081/api/user/1

###
GET http://localhost:8081/api/user/1/notice

###
PATCH http://localhost:8081/api/user/1/password
Content-Type: application/json

{
  "password": "12341234",
  "newPassword": "12349124"
}

###
GET http://localhost:8081/api/user
Content-Type: application/json

{
  "userName": "test",
  "phone" : "010-4939-2394"
}

###
GET http://localhost:8081/api/user/1/notice/like

###
POST http://localhost:8081/api/user/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "12341234"
}


###
PATCH http://localhost:8081/api/user/login
Content-Type: application/json
F-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwidXNlcl9pZCI6MSwiaXNzIjoidGVzdDJAdGVzdC5jb20iLCJleHAiOjE2MjM2NTA5NjV9.TA-cxM156D7k-NgYq7YqSIuR_8E4a5dVFoIncYxwxNQxCNQf82LwODv7PeVyVqXG1ITgsl5GyFp50EGTVTQbqA

###

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwidXNlcl9pZCI6MSwiaXNzIjoidGVzdDJAdGVzdC5jb20iLCJleHAiOjE2MjM2NTEwNjN9.Q9aAu3o6PIK7ds6bP01vSbh_u-cH7Qh3QEXDjz902FeA6Hs-csiJnc_6pVN1oZOw1dngpW1UZzh5_H6mAqG2C