POST http://localhost:8081/api/notice
Content-Type: application/json

{
  "title": "1112103120312032103103",
  "contents": "1112103120312214012041204012401240123-240215021502105120432103103-2-2-30",
  "userId": 1
}
###
POST http://localhost:8081/api/notice
Content-Type: application/json
{
  "title": "타이틀3",
  "contents": "contents4"
}

###
GET http://localhost:8081/api/notice/3

###
PUT http://localhost:8081/api/notice/1
Content-Type: application/json

{
  "title": "타이틀345",
  "contents": "contents345"
}

###
PATCH http://localhost:8081/api/notice/1/hits
Content-Type: application/json


###
DELETE http://localhost:8081/api/notice/1
Content-Type: application/json

###
DELETE http://localhost:8081/api/notice
Content-Type: application/json

{
  "idList": [1,2]
}

###
GET http://localhost:8081/api/notice/latest/3

###
POST http://localhost:8081/api/user
Content-Type: application/json

{
  "email" : "test2@test.com",
  "userName" : "test",
  "password" : "12341234",
  "phone" : "010-4939-2394"
}

###
PUT http://localhost:8081/api/user/2
Content-Type: application/json

{
"phone" : "010-1234-5678"
}

###
GET http://localhost:8081/api/user/1

###
GET http://localhost:8081/api/user/1/notice

###
PATCH http://localhost:8081/api/user/1/password
Content-Type: application/json

{
  "password": "12341234",
  "newPassword": "12349124"
}

###
GET http://localhost:8081/api/user
Content-Type: application/json

{
  "userName": "test",
  "phone" : "010-4939-2394"
}

###
GET http://localhost:8081/api/user/1/notice/like

###
POST http://localhost:8081/api/user/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "12341234"
}


###
PATCH http://localhost:8081/api/user/login
Content-Type: application/json
F-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwidXNlcl9pZCI6MSwiaXNzIjoidGVzdDJAdGVzdC5jb20iLCJleHAiOjE2MjM2NTA5NjV9.TA-cxM156D7k-NgYq7YqSIuR_8E4a5dVFoIncYxwxNQxCNQf82LwODv7PeVyVqXG1ITgsl5GyFp50EGTVTQbqA

###

GET http://localhost:8081/api/admin/user

###
GET http://localhost:8081/api/admin/user/1

###
GET http://localhost:8081/api/admin/user/search
Content-Type: application/json

{
  "email": "",
  "userName": "te",
  "phone": ""

}

###
PATCH http://localhost:8081/api/admin/user/1/status
Content-Type: application/json

{
  "status": 2
}

###
GET http://localhost:8081/api/admin/user/today

###
GET http://localhost:8081/api/admin/user/notice/count

###
GET http://localhost:8081/api/admin/user/log/count

###
GET http://localhost:8081/api/admin/user/like/best

###
POST http://localhost:8081/api/board/type
Content-Type: application/json

{
  "name": "게시판1"
}

###
PATCH http://localhost:8081/api/board/type/1/using
Content-Type: application/json

{
  "usingYn": true
}

###
PUT http://localhost:8081/api/board/type/1
Content-Type: application/json

{
  "name": "board_1"
}

###
GET http://localhost:8081/api/board/type

###
GET http://localhost:8081/api/board/type/count

###
POST http://localhost:8081/api/user/login
Content-Type: application/json

{
  "email" : "test1@test.com",
  "password" : "12341234"
}

###
PUT http://localhost:8081/api/board/1/hits
Content-Type: application/json
F-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MSIsInVzZXJfaWQiOjEsImlzcyI6InRlc3QxQHRlc3QuY29tIiwiZXhwIjoxNjI1MDYzODkwfQ.tcQNLyTMNsmtyj074HK3X78a5cz95washpWDz1HH_qOdPvifR6K-FHMRhCEoBtqbBjyITs74c3sMIGDwlMHXHw

###
PUT http://localhost:8081/api/board/1/like
Content-Type: application/json
F-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MSIsInVzZXJfaWQiOjEsImlzcyI6InRlc3QxQHRlc3QuY29tIiwiZXhwIjoxNjI1MDYzODkwfQ.tcQNLyTMNsmtyj074HK3X78a5cz95washpWDz1HH_qOdPvifR6K-FHMRhCEoBtqbBjyITs74c3sMIGDwlMHXHw

###
PUT http://localhost:8081/api/board/1/unlike
Content-Type: application/json
F-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MSIsInVzZXJfaWQiOjEsImlzcyI6InRlc3QxQHRlc3QuY29tIiwiZXhwIjoxNjI1MTI3NTIyfQ.LKGyXKmz6PQu6QLqP7mjp0vurEv1eNaG5YjUnGOrxthQvY-nnA4QJO2_o2Z2Wy0Hq2Ri0h9SS-HawxqIVI6WEQ

###
PUT http://localhost:8081/api/board/1/badreport
Content-Type: application/json
F-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MSIsInVzZXJfaWQiOjEsImlzcyI6InRlc3QxQHRlc3QuY29tIiwiZXhwIjoxNjI1MTI3NTIyfQ.LKGyXKmz6PQu6QLqP7mjp0vurEv1eNaG5YjUnGOrxthQvY-nnA4QJO2_o2Z2Wy0Hq2Ri0h9SS-HawxqIVI6WEQ

{
  "comments" : "불건전합니다"
}

###